# Generated by Django 4.2.1 on 2024-08-23 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0002_area_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Agentes.sector'),
        ),
    ]
