# Generated by Django 4.2.1 on 2024-08-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0003_agente_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='sector',
        ),
        migrations.AddField(
            model_name='agente',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Agentes.area'),
        ),
        migrations.AddField(
            model_name='area',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Agentes.sector'),
        ),
    ]
