# Generated by Django 4.2.1 on 2024-08-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0004_remove_agente_sector_agente_area_area_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=4)),
                ('diaCompensatorio', models.DateField()),
                ('horas', models.IntegerField()),
                ('detalle', models.CharField(max_length=100)),
                ('motivo', models.IntegerField(choices=[(0, 'A compensar'), (1, 'Compensar')])),
            ],
        ),
    ]
