# Generated by Django 4.2.1 on 2024-08-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0006_compensatorio_leg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensatorio',
            old_name='leg',
            new_name='nombreAgente',
        ),
        migrations.RemoveField(
            model_name='compensatorio',
            name='legajo',
        ),
    ]
