# Generated by Django 4.2.1 on 2024-08-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0007_rename_leg_compensatorio_nombreagente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensatorio',
            name='nombreAgente',
        ),
        migrations.AddField(
            model_name='compensatorio',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Agentes.agente'),
        ),
    ]
