# Generated by Django 4.2.1 on 2024-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0008_remove_compensatorio_nombreagente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compensatorio',
        ),
    ]
