# Generated by Django 4.2.1 on 2024-08-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0009_delete_compensatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=4)),
                ('diaCompensatorio', models.DateField()),
                ('horas', models.IntegerField()),
                ('detalle', models.CharField(max_length=100)),
                ('motivo', models.IntegerField(choices=[(0, 'A compensar'), (1, 'Compensar')])),
                ('nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Agentes.agente')),
            ],
        ),
    ]
