# Generated by Django 5.1 on 2024-09-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0013_vacaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacaciones',
            old_name='vaca',
            new_name='dias',
        ),
    ]
