# Generated by Django 4.2.1 on 2024-09-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0014_rename_vaca_vacaciones_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaCreacion', models.DateField()),
                ('diaArticulo', models.DateField()),
                ('cantidadDias', models.IntegerField()),
                ('cantidadHoras', models.TimeField()),
                ('parentesco', models.CharField(max_length=50)),
                ('com', models.CharField(max_length=100)),
                ('art155', models.CharField(max_length=100)),
                ('permiso', models.IntegerField(choices=[(0, 'Compensatorio**'), (1, 'Comisión***'), (2, 'Art. 155 (Trámite)****'), (3, 'Permiso Especial'), (4, 'Citación Judicial'), (5, 'Tomar'), (6, 'Donación de sangre'), (7, 'Licencia Ordinaria Anual'), (8, 'Licencia por Matrimonio'), (9, 'Licencia Matrimonio Hijos'), (10, 'Licencia Nacimiento Hijos'), (11, 'Licencia Examen'), (12, 'Licencia Fallecimiento de Pariente*')])),
                ('legajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agentes.agente')),
            ],
        ),
    ]
