# Generated by Django 5.1 on 2024-09-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0015_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art155',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cantidadDias',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cantidadHoras',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='com',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='parentesco',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
