# Generated by Django 4.2.1 on 2024-09-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0017_alter_articulo_art155_alter_articulo_cantidaddias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='permiso',
            field=models.IntegerField(choices=[(0, 'Compensatorio**'), (1, 'Comisión***'), (2, 'Art. 155 (Trámite)****'), (3, 'Permiso Especial'), (4, 'Citación Judicial'), (5, 'Donación de sangre'), (6, 'Licencia Ordinaria Anual'), (7, 'Licencia por Matrimonio'), (8, 'Licencia Matrimonio Hijos'), (9, 'Licencia Nacimiento Hijos'), (10, 'Licencia Examen'), (11, 'Licencia Fallecimiento de Pariente*')]),
        ),
    ]
