# Generated by Django 4.2.1 on 2024-09-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0018_alter_articulo_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='nitro',
            field=models.CharField(blank=True, choices=[(2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], max_length=30, null=True),
        ),
    ]
