# Generated by Django 4.2.1 on 2024-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0019_articulo_nitro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nitro',
            field=models.IntegerField(blank=True, choices=[(2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True),
        ),
    ]
